---
# check variables
# define the guest - create a kickstart file and virt-install shell script
# create the guest - run the script
# wait for install to complete.
# clean up
# Fail if no storage volume was created.

# !!! create the guest fails when disk already exists.
# Could do with a module to compare VM against requested state.
# assume a failure means the storage file is created and cached

# !!! create the guest may need a 5 second sleep
# got this 
# error while evaluating conditional (r_virt_status['status'] == 'shutdown'): 
# 'dict object' has no attribute 'status'.

# define 

- name: "Make kickstart file for VM {{ fqdn }}, {{ inventory_hostname }}:{{ kickstart_file_path }}/{{ kickstart_file_name }}"
  ansible.builtin.template:
    src: "{{ kickstart_file_template }}"
    dest: "{{ kickstart_file_path }}/{{ kickstart_file_name }}"
    owner: root
    group: root
    mode: '0644'
