---
# defaults file 

# The role expects to get some variables from vault and passed in vars.
# They are used in the kickstart template.

hostname: kshost

# # public network
# public_net_short_name: public
# public_libvirt_name: "net{{ public_net_short_name }}"
# public_nmcli_name: "bridge-{{ public_net_short_name }}"
# public_bridge_name: "br{{ public_net_short_name }}"
# public_mac_prefix: "52:54:00:00"

# # home network
# home_network: "192.168.1.0/24"
# home_domain: home

# host and lab network
kickstart_install_hostname: kshost
kickstart_install_lab_domain: example.com
kickstart_install_fqdn: "{{ kickstart_install_hostname }}.{{ kickstart_install_lab_domain }}"
kickstart_install_lab_net_short_name: lab
kickstart_install_lab_net_prefix: "192.168.123"
kickstart_install_lab_mac_prefix: "52:54:00:02"
#
kickstart_install_lab_libvirt_name:   "net{{ kickstart_install_lab_net_short_name }}"
kickstart_install_lab_nmcli_name: "bridge-{{ kickstart_install_lab_net_short_name }}"
kickstart_install_lab_bridge_name:     "br{{ kickstart_install_lab_net_short_name }}"
kickstart_install_lab_bridge_mac:        "{{ kickstart_install_lab_mac_prefix }}:00:01"
kickstart_install_lab_bridge_ip_cidr:    "{{ kickstart_install_lab_net_prefix }}.1/24"

# service
# send mail here
# relayhost: "message.{{ kickstart_install_lab_domain }}"

kickstart_install_file_path: "/var/tmp"
kickstart_install_file_name: "{{ kickstart_install_fqdn }}.ks"


# values for virt-install command
# --------
kickstart_install_config:
  fqdn: "{{ kickstart_install_fqdn }}"
  cpus: 2
  ram: 4096                           # size in MiB (4G * 1024 = 4096M)
  disk_size: 30                       # size in GiB
  nics:
    name: enp1s0
    mac: "{{ kickstart_install_lab_mac_prefix }}:00:99"
    ip: "{{ kickstart_install_lab_net_prefix }}.99"     # IP is static
    net: "{{ kickstart_install_lab_libvirt_name }}"
    gw: "{{ kickstart_install_lab_net_prefix }}.1"
  install_iso: /var/lib/libvirt/images/rhel-10.1-x86_64-dvd.iso
  # Use this command to get the list of accepted OS variants.
  #  virt-install --osinfo list
  os_variant: rhel10.1
  kickstart_install_file_path: "{{ kickstart_install_file_path }}"
  kickstart_install_file_name: "{{ kickstart_install_file_name }}"
# --------
